DJangoBackend/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('fetch_api.urls'))
]

fetch_api/urls.py
from django.conf.urls import url
from django.urls import path
from .views import GetNodesCount, GetNodeData, FetchComparisons, FetchNames, FetchKeyStories, index, results, graph

app_name = 'fetch_api'
urlpatterns = [
    path('', index, name='index'),
    path('results', results, name='results'),
    path('graph', graph, name='graph'),
    url(r'^fetch/count[/]?$', GetNodesCount.as_view(), name='get_nodes_count'),
    url(r'^fetch/nodes[/]?$', GetNodeData.as_view(), name='get_node_data'),
    url(r'^fetch/compare[/]?$', FetchComparisons.as_view(), name='fetch_comparisons'),
    url(r'^fetch/name[/]?$', FetchNames.as_view(), name='fetch_names'),
    url(r'^fetch/keystories[/]?$', FetchKeyStories.as_view(), name='fetch_key_stories'),
]

fetch_api/models/actor.py
from neomodel import (
    StringProperty,
    StructuredNode,
    RelationshipFrom
)


class Actor(StructuredNode):
    id = StringProperty(index=True)
    name = StringProperty()
    id = StringProperty()
    actor = RelationshipFrom('.actor.Actor', 'HAS_ACTOR')

fetch_api/models/date.py
from neomodel import (
    StringProperty,
    StructuredNode,
    RelationshipFrom
)


class Date(StructuredNode):
    id = StringProperty(index=True)
    text = StringProperty()
    type = StringProperty()
    entity = RelationshipFrom('.entity.Entity', 'HAS_ENTITY')

fetch_api/models/entity.py
from neomodel import (
    StringProperty,
    StructuredNode,
    RelationshipFrom
)

from .nodeutils import NodeUtils


class Entity(StructuredNode, NodeUtils):
    id = StringProperty(index=True)
    text = StringProperty()
    type = StringProperty()
    entity = RelationshipFrom('.entity.Entity', 'HAS_ENTITY')

    @property
    def serialize(self):
        return {
            'node_properties': {
                'id': self.id,
                'text': self.text,
                'type': self.type,
            },
        }

    @property
    def serialize_connections(self):
        return [
            {
                'nodes_type': 'Entity',
                'nodes_related': self.serialize_relationships(self.entity.all()),
            },
        ]


class Quantity(Entity):
    identity = StringProperty(index=True)
    text = StringProperty()
    type = StringProperty()
    entity = RelationshipFrom('.entity.Entity', 'HAS_ENTITY')

    @property
    def serialize(self):
        return {
            'node_properties': {
                'id': self.id,
                'text': self.text,
                'type': self.type,
            },
        }

    @property
    def serialize_connections(self):
        return [
            {
                'nodes_type': 'Entity',
                'nodes_related': self.serialize_relationships(self.entity.all()),
            },
        ]


class Other(Entity):
    identity = StringProperty(index=True)
    text = StringProperty()
    type = StringProperty()
    entity = RelationshipFrom('.entity.Entity', 'HAS_ENTITY')

    @property
    def serialize(self):
        return {
            'node_properties': {
                'id': self.id,
                'text': self.text,
                'type': self.type,
            },
        }

    @property
    def serialize_connections(self):
        return [
            {
                'nodes_type': 'Entity',
                'nodes_related': self.serialize_relationships(self.entity.all()),
            },
        ]


class Person(Entity):
    id = StringProperty(index=True)
    text = StringProperty()
    type = StringProperty()
    entity = RelationshipFrom('.entity.Entity', 'HAS_ENTITY')

    @property
    def serialize(self):
        return {
            'node_properties': {
                'id': self.id,
                'text': self.text,
                'type': self.type,
            },
        }

    @property
    def serialize_connections(self):
        return [
            {
                'nodes_type': 'Entity',
                'nodes_related': self.serialize_relationships(self.entity.all()),
            },
        ]

fetch_api/models/keyphrase.py
from neomodel import (
    StringProperty,
    StructuredNode,
    RelationshipFrom
)

from .nodeutils import NodeUtils


class KeyPhrase(StructuredNode, NodeUtils):
    id = StringProperty(index=True)
    text = StringProperty()
    keyphrase = RelationshipFrom('.keyphrase.KeyPhrase', 'HAS_KEYPHRASE')

    @property
    def serialize(self):
        return {
            'node_properties': {
                'id': self.id,
                'text': self.text,
            },
        }

    @property
    def serialize_connections(self):
        return [
            {
                'nodes_type': 'KeyPhrase',
                'nodes_related': self.serialize_relationships(self.keyphrase.all()),
            },

        ]

fetch_api/models/nodeutils.py
from abc import ABCMeta
from neomodel import db


class NodeUtils:
    __metaclass__ = ABCMeta

    def serialize_relationships(self, nodes):
        serialized_nodes = []
        for node in nodes:
            # serialize node
            serialized_node = node.serialize

            # UNCOMMENT to get relationship type
            # results, colums = self.cypher('''
            #     START start_node=node({self}), end_node=node({end_node})
            #     MATCH (start_node)-[rel]-(end_node)
            #     RETURN type(rel) as node_relationship
            #     ''',
            #     {'end_node': node.id}
            # )
            # serialized_node['node_relationship'] = results[0][0]

            serialized_nodes.append(serialized_node)

        return serialized_nodes

fetch_api/models/organization.py
from neomodel import (
    StringProperty,
    StructuredNode,
    RelationshipFrom
)


class Organization(StructuredNode):
    id = StringProperty(index=True)
    text = StringProperty()
    type = StringProperty()
    entity = RelationshipFrom('.entity.Entity', 'HAS_ENTITY')

fetch_api/models/platform.py
from neomodel import (
    StringProperty,
    StructuredNode,
    Relationship
)


class Platform(StructuredNode):
    id = StringProperty(index=True)
    name = StringProperty()
    entity = Relationship('.entity.Entity', 'HAS_ENTITY')

fetch_api/models/story.py
from neomodel import (
    StringProperty,
    StructuredNode,
    RelationshipTo
)

from .nodeutils import NodeUtils


class Story(StructuredNode, NodeUtils):
    nodeID = StringProperty(index=True)
    sentimentScore = StringProperty()
    sentiment = StringProperty()
    notes = StringProperty()
    name = StringProperty()
    value = StringProperty()
    acceptance_criteria = StringProperty()
    keyphrase = RelationshipTo('.keyphrase.KeyPhrase', 'HAS_KEYPHRASE')
    entity = RelationshipTo('.entity.Entity', 'HAS_ENTITY')
    actor = RelationshipTo('.actor.Actor', 'HAS_ACTOR')
    platform = RelationshipTo('.platform.Platform', 'HAS_PLATFORM')

    @property
    def serialize(self):
        return {
            'node_properties': {
                'id': self.nodeID,
                'sentimentScore': self.sentimentScore,
                'sentiment': self.sentiment,
                'notes': self.notes,
                'name': self.name,
                'value': self.value,
                'acceptance_criteria': self.acceptance_criteria,
            },
        }

    @property
    def serialize_connections(self):
        return [
            {
                'nodes_type': 'KeyPhrase',
                'nodes_related': self.serialize_relationships(self.kephrase.all()),
            },
            {
                'nodes_type': 'Entity',
                'nodes_related': self.serialize_relationships(self.entity.all()),
            },
            {
                'nodes_type': 'Actor',
                'nodes_related': self.serialize_relationships(self.actor.all()),
            },
            {
                'nodes_type': 'Platform',
                'nodes_related': self.serialize_relationships(self.platform.all()),
            },
        ]

fetch_api/forms.py
from django import forms


class SprintForm(forms.Form):
    duration = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'How long do you have?'
    }))
    num_stories = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'How many stories?'
    }))
    actors = forms.CharField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'How many people?'
    }))

fetch_api/views.py
from django.shortcuts import render

from .utils import (
    count_nodes,
    fetch_nodes,
    fetch_node_details,
    fetch_names,
    fetch_comparisons,
    fetch_key_stories,
)
# Create your views here.

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .utils import fetch_nodes


class FetchComparisons(APIView):
    def get(self, request):
        fetch_compare = {
            'name': request.GET.get('n', 'Sub Epics'),
        }
        comparison = fetch_comparisons(fetch_compare)
        data = {
            'response': {
                'status': '200',
                'rows': len(comparison),
                'data': comparison,
            },
        }
        return Response(data)


class FetchKeyStories(APIView):
    def get(self, request):
        fetch_stories = {
            'name': request.GET.get('n', 'details and verbiage'),
        }
        stories = fetch_key_stories(fetch_stories)
        data = {
            'response': {
                'status': '200',
                'rows': len(stories),
                'data': stories,
            },
        }
        return Response(data)


class FetchNames(APIView):
    def get(self, request):
        names = fetch_names()
        data = {
            'response': {
                'status': '200',
                'rows': len(names),
                'data': names,
            },
        }
        return Response(data)


class GetNodesCount(APIView):
    def get(self, request):
        fetch_info = {
            'node_type': request.GET.get('t', 'Story'),
            'name': request.GET.get('n', ''),
            'notes': request.GET.get('no', ''),
            'value': request.GET.get('v', ''),
            'text': request.GET.get('txt', ''),
            'type': request.GET.get('ty', ''),
            'limit': 10,
            'page': int(request.GET.get('p', 1)),
        }
        count = count_nodes(fetch_info)
        data = {
            'response': {
                'status': '200',
                'data': count,
            },
        }
        return Response(data)


class GetNodeData(APIView):
    def get(self, request):
        fetch_info = {
            'node_type': request.GET.get('t', 'Story'),
            'name': request.GET.get('n', ''),
            'notes': request.GET.get('no', ''),
            'value': request.GET.get('v', ''),
            'text': request.GET.get('txt', ''),
            'type': request.GET.get('ty', ''),
            'limit': request.GET.get('l', "10"),
            'page': int(request.GET.get('p', 1)),
        }
        nodes = fetch_nodes(fetch_info)
        data = {
            'response': {
                'status': '200',
                'rows': len(nodes),
                'data': nodes,
            },
        }
        return Response(data)

fetch_api/views/api.py
from rest_framework.response import Response
from rest_framework.views import APIView

from fetch_api.utils import (
    count_nodes,
    fetch_names,
    fetch_comparisons,
    fetch_key_stories,
)
from fetch_api.utils import fetch_nodes


# Create your views here.


class FetchComparisons(APIView):
    def get(self, request):
        fetch_compare = {
            'name': request.GET.get('n', 'Sub Epics'),
        }
        comparison = fetch_comparisons(fetch_compare)
        data = {
            'response': {
                'status': '200',
                'rows': len(comparison),
                'data': comparison,
            },
        }
        return Response(data)


class FetchKeyStories(APIView):
    def get(self, request):
        fetch_stories = {
            'name': request.GET.get('n', 'details and verbiage'),
        }
        stories = fetch_key_stories(fetch_stories)
        data = {
            'response': {
                'status': '200',
                'rows': len(stories),
                'data': stories,
            },
        }
        return Response(data)


class FetchNames(APIView):
    def get(self, request):
        names = fetch_names()
        data = {
            'response': {
                'status': '200',
                'rows': len(names),
                'data': names,
            },
        }
        return Response(data)


class GetNodesCount(APIView):
    def get(self, request):
        fetch_info = {
            'node_type': request.GET.get('t', 'Story'),
            'name': request.GET.get('n', ''),
            'notes': request.GET.get('no', ''),
            'value': request.GET.get('v', ''),
            'text': request.GET.get('txt', ''),
            'type': request.GET.get('ty', ''),
            'limit': 10,
            'page': int(request.GET.get('p', 1)),
        }
        count = count_nodes(fetch_info)
        data = {
            'response': {
                'status': '200',
                'data': count,
            },
        }
        return Response(data)


class GetNodeData(APIView):
    def get(self, request):
        fetch_info = {
            'node_type': request.GET.get('t', 'Story'),
            'name': request.GET.get('n', ''),
            'notes': request.GET.get('no', ''),
            'value': request.GET.get('v', ''),
            'text': request.GET.get('txt', ''),
            'type': request.GET.get('ty', ''),
            'limit': request.GET.get('l', "10"),
            'page': int(request.GET.get('p', 1)),
        }
        nodes = fetch_nodes(fetch_info)
        data = {
            'response': {
                'status': '200',
                'rows': len(nodes),
                'data': nodes,
            },
        }
        return Response(data)

fetch_api/views/sprint.py
from django.shortcuts import render, redirect

from fetch_api.forms import SprintForm
from fetch_api.models import Story


def index(request):
    context = {'form': SprintForm()}
    return render(request, 'sprint/index.html', context=context)


def results(request):
    if request.method == "POST":
        form = SprintForm(request.POST)
        if form.is_valid():
            stories = Story.nodes.all()[0:form.cleaned_data['num_stories']]
            return render(request, 'sprint/results.html', context={'stories': stories})
        else:
            return render(request, 'sprint/index.html', context={'form': form})
    else:
        return redirect(to='fetch_api:index')


def graph(request):
    return redirect(to='fetch_api:index')

fetch_api/templates/sprint/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Project Management
{% endblock %}

{% block additional_css %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
{% endblock %}

{% block body %}
    <body class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
            <h3>Welcome!</h3>
            <p>This is a Project Management App!</p>
            <p>Find out the Optimal Path to your Project!</p>
        </div>
        <div class="col-md-9 register-right">

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="register-heading">Fill out the information below!</h3>
                    <div class="row register-form">

                        <div class="col-md-6">
                            <div class="explain">
                                <p>.</p>
                                <p style="text-align:center"><u>Welcome to the Project Management App!</u></p>
                                <p style="text-align:center">This application runs on a Django framework
                                    and will be able to find the most optimal path through the use of Ai. Once
                                    complete
                                    you will have the
                                    opportunity to view the suggestion in graph form.</p>
                                <p>.</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <form action="{% url 'fetch_api:results' %}" method="post">
                                {{ form.errors }}
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.duration }}
                                </div>
                                <div class="form-group">
                                    {{ form.num_stories }}
                                </div>
                                <div class="form-group">
                                    {{ form.actors }}
                                </div>
                                <input type="submit" class="btnRegister" value="Suggest!"/>
                            </form>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    </body>
{% endblock %}


     

fetch_api/templates/sprint/results.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Project Management
{% endblock %}

{% block additional_css %}
    <link href="{% static 'css/results.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/BinPacking.min.js' %}"></script>
{% endblock %}

{% block body %}
    <body class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
            <h3>Here are the Results!</h3>

            <p>The results on the right are the most optimal path for this project. <br>
                <br> Click the Graph button to see a visual representation of your results. Or click home to try
                different inputs</p>

        </div>
        <div class="col-md-9 register-right">

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="register-heading">Final Results:</h3>
                    <div class="row register-form">


                        <div class="explain">
                            <span style="display:inline-block;"></span>

                            <ul>
                                {% for story in stories %}
                                    <li>{{ story.name }}</li>
                                {% endfor %}
                            </ul>

                        </div>

                    </div>
                    <!--This will take you to the Graph html so change the href-->
                    <a href="{% url 'fetch_api:graph' %}">
                        <input type="button" style="float:right " onclick="" class="btnRegister" value="Graph"/>
                    </a>
                    <!--Takes u to the previous page using history.
                        For Graph might want to make -1 into -2 to go back to home page and -1 to go back to results-->
                    <a href="{% url 'fetch_api:index' %}">
                        <input type="button" style="float:right" class="btnRegister" value="Home"/>
                    </a>
                </div>

            </div>
        </div>
    </div>
    <canvas class="graph" id="explain-canvas"></canvas>
    <script src="{% static 'js/diagram.js' %}"></script>
    </body>
{% endblock %}
     